layout: sidebar
style: dark

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

projects:
  sort_by: stars
  # sort_by options:
  #   - pushed
  #   - stars
  limit: 9
  exclude:
    archived: false
    forks: true
    projects: -test

        # - repo-name

social_media:
  # behance: your_username
  # dribbble: your_username
  facebook: lahiru.senevirathna.95
  # hackerrank: your_username
  instagram: lahiru_senevirathne
  # keybase: your_username
  linkedin: lahirusenevirathna
  # mastodon: your_username
  # medium: your_username
  stackoverflow: 8967062
  # telegram: your_username
  twitter: LahiruCSE
  # unsplash: your_username
  # vk: your_username
  # website: http://your_website_url
  # youtube: your_username

topics:
  - name: Python
    web_url: https://www.python.org/
    image_url: https://www.python.org/static/img/python-logo.png

  - name: Spring Boot
    web_url: https://spring.io/projects/spring-boot
    image_url: https://spring.io/images/spring-logo-9146a4d3298760c2e7e49595184e1975.svg

  - name: Angular
    web_url: https://angular.io/
    image_url: https://cdn.worldvectorlogo.com/logos/angular-icon.svg

  - name: Keras
    web_url: https://keras.io/
    image_url: https://upload.wikimedia.org/wikipedia/commons/c/c9/Keras_Logo.jpg

  - name: AWS
    web_url: https://aws.amazon.com/
    image_url: https://a0.awsstatic.com/libra-css/images/logos/aws_logo_smile_1200x630.png

